# Generated by Django 4.1.3 on 2023-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='baon.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
