# Generated by Django 4.1.3 on 2023-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_product_uxod_za_veshyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uxod_za_veshyu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
