# Generated by Django 4.1.3 on 2023-05-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_alter_product_uxod_za_veshyu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uxod_za_veshyu',
        ),
    ]
