# Generated by Django 4.1.3 on 2023-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_product_uxod_za_veshyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uxozaveshyu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
