# Generated by Django 4.1.3 on 2023-05-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_product_uxozaveshyu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='additives',
            new_name='ciferblat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='expiration_date',
            new_name='data_okonchaniya_sroka',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='armchair_size',
            new_name='dobavki',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brake_type',
            new_name='klass_korma',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='maximum_load',
            new_name='maksimalnaya_zagruska',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='coating',
            new_name='material_rami',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='contraindications',
            new_name='pokritiye',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='edition',
            new_name='protivopokazaniya',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feed_class',
            new_name='razmer_kresla',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='frame_material',
            new_name='stil_yezdi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='riding_style',
            new_name='tip_povadka',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='taste',
            new_name='tip_stekla',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_of_depreciation',
            new_name='tip_tormoza',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_of_food_taste',
            new_name='tip_vkusa_edi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_of_glass',
            new_name='uxod_za_veshyu',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_of_leash',
            new_name='versiya',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='watch_face',
            new_name='vid_amortizaciyi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uxozaveshyu',
            new_name='vkus',
        ),
    ]
