# Generated by Django 4.1.3 on 2023-05-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_remove_product_age_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
