# Generated by Django 4.1.3 on 2023-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_rename_nineshnaya_cena_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_height',
            field=models.IntegerField(null=True),
        ),
    ]
